name: Publish packages

on:
  push:
    tags:
    - 'v**'
    - 'nightly'
permissions:
  contents: read
jobs:
  build_cedarling_wasm:
    runs-on: ubuntu-20.04
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
      with:
        egress-policy: audit

    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Build WASM build
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      id: sign-cedarling
      working-directory: ${{ github.workspace }}/jans-cedarling/bindings/cedarling_wasm
      run: |
        rustup update stable && rustup default stable
        cargo install wasm-pack
        wasm-pack build --release --target web --scope janssenproject
        ls pkg
        cd pkg
        npm publish --access public
